"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowDown, Clock, GitBranch, GripHorizontal, Mic, MessageSquare, MessagesSquare, Play, Plus, Save, Trash2, Workflow, X } from "lucide-react";
import { supabase } from "@/lib/supabase-client";
import type { Profile, WhatsappNumber } from "@/lib/types";
import { matches, nextNode, renderText, validateFlow, type AutomationFlow, type AutomationNode } from "@/whatsapp-service/src/automation-flow.js";
import AutomationAudio from "./AutomationAudio";
type ConversationOption={id:string;numberId:string|null;label:string};
type Rule={id?:string;name:string;number_id:string;enabled:boolean;trigger_type:'incoming'|'scheduled';match_mode:'any'|'contains'|'exact';keywords:string;cooldown_minutes:number;priority:number;pause_on_human:boolean;scheduled_at:string|null;target_conversation_id:string|null;flow:AutomationFlow};
type Run={id:string;automation_name:string;contact_name:string;status:string;created_at:string;due_at:string;error:string|null;steps_done:number};
const DEFS={start:{name:'Início',icon:Play,color:'#6366f1'},text:{name:'Enviar texto',icon:MessageSquare,color:'#10b981'},audio:{name:'Enviar áudio',icon:Mic,color:'#0ea5e9'},condition:{name:'Condição',icon:GitBranch,color:'#a855f7'},delay:{name:'Aguardar',icon:Clock,color:'#f59e0b'},reply:{name:'Esperar resposta',icon:MessagesSquare,color:'#06b6d4'},end:{name:'Fim',icon:Workflow,color:'#64748b'}};
const uid=()=>crypto.randomUUID();
function initialFlow():AutomationFlow{return {nodes:[{id:'start',type:'start',x:40,y:100,data:{}},{id:'text',type:'text',x:330,y:100,data:{text:'Olá, {{nome}}! Como podemos ajudar?'}},{id:'end',type:'end',x:620,y:100,data:{}}],edges:[{id:'e1',from:'start',to:'text',handle:'out'},{id:'e2',from:'text',to:'end',handle:'out'}]};}
const handles=(n:AutomationNode)=>n.type==='end'?[]:n.type==='condition'?['yes','no']:n.type==='reply'?['reply','timeout']:['out'];
const handleName=(h:string)=>h==='yes'?'Sim':h==='no'?'Não':h==='reply'?'Respondeu':h==='timeout'?'Sem resposta':'Próxima etapa';
const inputClass='w-full rounded-lg border border-white/10 bg-[#0b1422] p-2.5 text-sm outline-none focus:border-emerald-500/50';
function localDate(iso:string|null){if(!iso)return '';const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export default function MessageAutomations({profile,numbers,conversations,initialNumber,onClose}:{profile:Profile;numbers:WhatsappNumber[];conversations:ConversationOption[];initialNumber:string|null;onClose:()=>void}) {
 const canEdit=profile.role==='gestor'||profile.role==='gerente';
 const [rules,setRules]=useState<Rule[]>([]),[runs,setRuns]=useState<Run[]>([]),[draft,setDraft]=useState<Rule|null>(null),[selected,setSelected]=useState('start'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[showRuns,setShowRuns]=useState(false),[link,setLink]=useState<{from:string;handle:string}|null>(null),[example,setExample]=useState('Olá'),[simulation,setSimulation]=useState<string[]>([]);
 const [audioBusy,setAudioBusy]=useState(false);
 const drag=useRef<{id:string;pointer:number;x:number;y:number;nx:number;ny:number}|null>(null);
 const load=useCallback(async()=>{if(!supabase||!profile.company_id)return;const [r,h]=await Promise.all([supabase.from('message_automations').select('*').eq('company_id',profile.company_id).order('priority').order('created_at'),canEdit?supabase.from('message_automation_runs').select('id,automation_name,contact_name,status,created_at,due_at,error,steps_done').eq('company_id',profile.company_id).order('created_at',{ascending:false}).limit(50):Promise.resolve({data:[],error:null})]);setRules(r.data??[]);setRuns(h.data??[]);setLoading(false);if(r.error||h.error)setError(r.error?.message||h.error?.message||'Falha ao carregar.');},[profile.company_id,canEdit]);
 useEffect(()=>{void Promise.resolve().then(load);},[load]);
 useEffect(()=>{if(!showRuns)return;const timer=setInterval(()=>void load(),10000);return()=>clearInterval(timer);},[load,showRuns]);
 function newRule(){setDraft({name:'Novo fluxo',number_id:initialNumber||numbers[0]?.id||'',enabled:false,trigger_type:'incoming',match_mode:'any',keywords:'',cooldown_minutes:1440,priority:100,pause_on_human:true,scheduled_at:null,target_conversation_id:null,flow:initialFlow()});setSelected('start');setError('');setNotice('');setSimulation([]);setLink(null);}
 function patch(p:Partial<Rule>){setDraft(d=>d?{...d,...p}:d);setNotice('');setSimulation([]);}
 function patchNode(id:string,data:Partial<AutomationNode['data']>){setDraft(d=>d?{...d,flow:{...d.flow,nodes:d.flow.nodes.map(n=>n.id===id?{...n,data:{...n.data,...data}}:n)}}:d);setNotice('');setSimulation([]);}
 function connect(from:string,handle:string,to:string){if(from===to||to==='start'){setError('Escolha outra etapa para conectar.');return;}setDraft(d=>d?{...d,flow:{...d.flow,edges:[...d.flow.edges.filter(e=>!(e.from===from&&e.handle===handle)),{id:uid(),from,to,handle}]}}:d);setLink(null);setNotice('');setSimulation([]);}
 function add(type:AutomationNode['type']){if(!draft||draft.flow.nodes.length>=30)return;const id=uid(),source=draft.flow.nodes.find(n=>n.id===selected)||draft.flow.nodes[0];const edge=source.type==='end'?draft.flow.edges.find(e=>e.to===source.id):draft.flow.edges.find(e=>e.from===source.id);const pos=draft.flow.nodes.length;const node:AutomationNode={id,type,x:40+(pos%4)*290,y:100+Math.floor(pos/4)*190,data:type==='text'?{text:''}:type==='delay'?{minutes:1}:type==='reply'?{minutes:1440}:type==='condition'?{mode:'contains',keywords:''}:{}};const oldTo=edge?.to||draft.flow.nodes.find(n=>n.type==='end')?.id;let edges=draft.flow.edges.filter(e=>e.id!==edge?.id);if(edge)edges=[...edges,{...edge,to:id}];if(oldTo)edges=[...edges,...handles(node).map(h=>({id:uid(),from:id,handle:h,to:oldTo}))];patch({flow:{nodes:[...draft.flow.nodes,node],edges}});setSelected(id);}
 function organize(){if(!draft)return;const indegree=new Map(draft.flow.nodes.map(n=>[n.id,0])),rank=new Map<string,number>();for(const e of draft.flow.edges)indegree.set(e.to,(indegree.get(e.to)||0)+1);const queue=draft.flow.nodes.filter(n=>!indegree.get(n.id)).map(n=>n.id);let count=0;while(queue.length){const id=queue.shift()!;count++;for(const e of draft.flow.edges.filter(e=>e.from===id)){rank.set(e.to,Math.max(rank.get(e.to)||0,(rank.get(id)||0)+1));indegree.set(e.to,(indegree.get(e.to)||0)-1);if(!indegree.get(e.to))queue.push(e.to);}}if(count!==draft.flow.nodes.length){setError('Remova conexões em ciclo para organizar.');return;}const rows=new Map<number,number>();patch({flow:{...draft.flow,nodes:draft.flow.nodes.map(n=>{const r=rank.get(n.id)||0,y=rows.get(r)||0;rows.set(r,y+1);return {...n,x:40+r*290,y:60+y*180};})}});}
 function removeNode(id:string){if(!draft||draft.flow.nodes.find(n=>n.id===id)?.type==='start')return;patch({flow:{nodes:draft.flow.nodes.filter(n=>n.id!==id),edges:draft.flow.edges.filter(e=>e.from!==id&&e.to!==id)}});setSelected('start');}
 async function save(){if(!draft||!supabase||!profile.company_id)return;setError('');const invalid=validateFlow(draft.flow,new URL(process.env.NEXT_PUBLIC_SUPABASE_URL!).origin,profile.company_id);if(invalid){setError(invalid);return;}if(!draft.name.trim()||!draft.number_id){setError('Informe o nome e o número do WhatsApp.');return;}if(draft.trigger_type==='incoming'&&draft.match_mode!=='any'&&!draft.keywords.trim()){setError('Informe as palavras do gatilho.');return;}if(draft.trigger_type==='scheduled'&&(!draft.scheduled_at||!draft.target_conversation_id||(draft.enabled&&new Date(draft.scheduled_at).getTime()<=Date.now()))){setError('Escolha um contato e uma data/hora futura.');return;}setBusy(true);try{const {id,...body}=draft;const payload={...body,name:body.name.trim(),company_id:profile.company_id};const r=id?await supabase.from('message_automations').update(payload).eq('id',id).select('*').single():await supabase.from('message_automations').insert({...payload,created_by:profile.id}).select('*').single();if(r.error)throw r.error;setDraft(r.data);setNotice('Fluxo salvo. '+(r.data.enabled?'Automação ativa.':'Automação pausada.'));await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}}
 async function toggle(rule:Rule){if(!supabase||!rule.id)return;if(!rule.enabled&&rule.trigger_type==='scheduled'&&(!rule.scheduled_at||new Date(rule.scheduled_at).getTime()<=Date.now())){setError('Edite o fluxo e escolha uma nova data futura para ativar.');return;}setBusy(true);const {error:e}=await supabase.from('message_automations').update({enabled:!rule.enabled}).eq('id',rule.id);if(e)setError(e.message);await load();setBusy(false);}
 async function remove(rule:Rule){if(!supabase||!rule.id||!confirm('Excluir este fluxo? As execuções ficam no histórico.'))return;setBusy(true);const {error:e}=await supabase.from('message_automations').delete().eq('id',rule.id);if(e)setError(e.message);await load();setBusy(false);}
 function simulate(){if(!draft)return;const invalid=validateFlow(draft.flow);if(invalid){setError(invalid);return;}setError('');const steps:string[]=[];let id:string|null=draft.flow.nodes.find(n=>n.type==='start')!.id;while(id&&steps.length<30){const n=draft.flow.nodes.find(node=>node.id===id)!;steps.push(n.type==='text'?renderText(n.data.text!,'Cliente'):n.type==='audio'?'Enviar áudio gravado':n.type==='delay'?`Aguardar ${n.data.minutes} minuto(s)`:n.type==='reply'?`Esperar resposta (até ${n.data.minutes} minutos)`:n.type==='condition'?`Condição: ${matches(n.data.mode!,n.data.keywords!,example)?'Sim':'Não'}`:DEFS[n.type].name);id=nextNode(draft.flow,n.id,n.type==='condition'?(matches(n.data.mode!,n.data.keywords!,example)?'yes':'no'):n.type==='reply'?'reply':'out');}setSimulation(steps);}
 const current=draft?.flow.nodes.find(n=>n.id===selected);
 const statusNames:Record<string,string>={queued:'Agendada / aguardando',waiting_reply:'Esperando resposta',running:'Executando',completed:'Concluída',failed:'Falhou',canceled:'Cancelada'};
 return <div className="fixed inset-0 z-[120] bg-[#080f1b] flex flex-col text-slate-100" role="dialog" aria-modal="true" aria-label="Automações do WhatsApp">
  <header className="shrink-0 flex items-center gap-3 px-4 py-3 border-b border-white/10"><Workflow size={21} className="text-emerald-400"/><div className="flex-1 min-w-0"><h2 className="font-semibold">Automações do WhatsApp</h2><p className="text-[11px] text-slate-400">Fluxos de texto e áudio · respostas automáticas e agendamentos</p></div><button aria-label="Fechar automações" disabled={busy||audioBusy} onClick={onClose} className="p-2 rounded-lg hover:bg-white/10"><X size={20}/></button></header>
  {error&&<p role="alert" className="shrink-0 p-3 text-sm text-red-300 bg-red-500/10">{error}</p>}{notice&&<p role="status" className="shrink-0 p-3 text-sm text-emerald-300 bg-emerald-500/10">{notice}</p>}
  {!draft?<div className="flex-1 overflow-y-auto p-4 md:p-8 max-w-6xl w-full mx-auto">
   <div className="flex flex-wrap gap-2 mb-5"><button onClick={()=>{setShowRuns(false);setError('');}} className={`px-4 py-2 rounded-lg ${!showRuns?'bg-white/10':''}`}>Meus fluxos</button>{canEdit&&<button onClick={()=>{setShowRuns(true);void load();}} className={`px-4 py-2 rounded-lg ${showRuns?'bg-white/10':''}`}>Execuções</button>}{canEdit&&<button disabled={!numbers.length} onClick={newRule} className="ml-auto flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 disabled:opacity-50"><Plus size={16}/>Novo fluxo</button>}</div>
   {!canEdit&&<p className="text-sm text-slate-400 mb-4">A gestão configura e ativa as automações da empresa.</p>}
   {!numbers.length&&<p className="text-slate-400">Cadastre um número de WhatsApp para criar automações.</p>}
   {loading?<p>Carregando…</p>:showRuns?<div className="space-y-3">{!runs.length&&<p className="text-slate-400">As execuções aparecerão aqui quando um fluxo for acionado.</p>}{runs.map(r=><div key={r.id} className="p-4 rounded-xl border border-white/10 bg-[#101b2d]"><div className="flex flex-wrap gap-2 justify-between"><strong className="text-sm">{r.automation_name} · {r.contact_name}</strong><span className={`text-xs ${r.status==='failed'?'text-red-300':'text-emerald-300'}`}>{statusNames[r.status]}</span></div><p className="text-xs text-slate-400 mt-1">{new Date(r.created_at).toLocaleString()} · {r.steps_done} etapa(s) concluída(s){r.status==='queued'?` · próxima execução: ${new Date(r.due_at).toLocaleString()}`:''}</p>{r.error&&<p className="text-xs text-amber-300 mt-2">{r.error}</p>}</div>)}</div>:<>
    {!rules.length&&<div className="py-12 text-center rounded-xl border border-dashed border-white/15"><Workflow size={40} className="mx-auto text-emerald-400 mb-3"/><h3 className="font-semibold">Monte sua primeira automação</h3><p className="text-sm text-slate-400 mt-2">Receba uma mensagem, verifique a condição e envie textos ou áudios em sequência.</p></div>}
    <div className="grid md:grid-cols-2 gap-4">{rules.map(r=><div key={r.id} className="rounded-xl border border-white/10 bg-[#101b2d] p-4 space-y-3"><div className="flex items-center gap-2"><h3 className="font-semibold flex-1 truncate">{r.name}</h3><span className={`text-[11px] rounded-full px-2 py-1 ${r.enabled?'text-emerald-300 bg-emerald-500/10':'text-slate-400 bg-white/5'}`}>{r.enabled?'Ativa':'Pausada'}</span></div><p className="text-xs text-slate-400">{numbers.find(n=>n.id===r.number_id)?.label} · {r.trigger_type==='scheduled'?`Agendada: ${new Date(r.scheduled_at!).toLocaleString()}`:r.match_mode==='any'?'Ao receber qualquer mensagem':`Quando a mensagem ${r.match_mode==='exact'?'for igual a':'contiver'}: ${r.keywords.split('\n').join(', ')}`}</p><p className="text-[11px] text-slate-500">{r.flow.nodes.length} etapas · prioridade {r.priority}</p>{canEdit&&<div className="flex gap-2"><button onClick={()=>{setDraft(structuredClone(r));setSelected(r.flow.nodes.find(n=>n.type==='start')?.id||'start');setError('');setSimulation([]);setNotice('');}} className="px-3 py-2 rounded-lg bg-white/10 text-xs">Editar fluxo</button><button disabled={busy||audioBusy} onClick={()=>void toggle(r)} className="px-3 py-2 rounded-lg bg-emerald-600/20 text-emerald-300 text-xs">{r.enabled?'Pausar':'Ativar'}</button><button disabled={busy||audioBusy} aria-label={`Excluir ${r.name}`} onClick={()=>void remove(r)} className="ml-auto p-2 text-slate-400"><Trash2 size={16}/></button></div>}</div>)}</div>
    <p className="text-xs text-slate-500 mt-6">Quando várias regras combinarem, será usada a primeira por prioridade (menor número primeiro). O histórico registra esperas, conclusão e falhas.</p>
   </>}
  </div>:<>
   <div className="shrink-0 p-3 border-b border-white/10 flex flex-wrap items-center gap-2"><button disabled={busy||audioBusy} onClick={()=>{if(confirm('Voltar à lista? Alterações não salvas serão descartadas.')){setDraft(null);setError('');setNotice('');}}} className="px-3 py-2 rounded-lg bg-white/5 text-xs">Voltar</button><input aria-label="Nome do fluxo" maxLength={100} value={draft.name} onChange={e=>patch({name:e.target.value})} className={`${inputClass} flex-1 min-w-32 max-w-sm`}/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={draft.enabled} onChange={e=>patch({enabled:e.target.checked})}/>Ativa</label><button disabled={busy||audioBusy} onClick={()=>void save()} className="flex items-center gap-2 px-4 py-2 rounded-lg bg-emerald-600 text-sm disabled:opacity-50"><Save size={16}/>{busy?'Salvando…':'Salvar fluxo'}</button></div>
   <div className="flex-1 min-h-0 flex flex-col md:flex-row overflow-y-auto md:overflow-hidden">
    <section className="h-[420px] shrink-0 md:h-auto md:flex-1 min-w-0 flex flex-col min-h-0">
     <div className="flex flex-wrap gap-2 p-3 border-b border-white/10"><button onClick={organize} className="flex items-center gap-1.5 rounded-lg bg-emerald-500/10 text-emerald-300 px-2 py-2 text-xs"><Workflow size={15}/>Organizar</button>{(['text','audio','condition','delay','reply','end'] as AutomationNode['type'][]).map(t=>{const Icon=DEFS[t].icon;return <button key={t} onClick={()=>add(t)} className="flex items-center gap-1.5 rounded-lg bg-white/5 px-2 py-2 text-xs hover:bg-white/10"><Icon size={15} style={{color:DEFS[t].color}}/>{DEFS[t].name}</button>;})}</div>
     <p className="px-3 py-2 text-[11px] text-slate-400">{link?`Toque na entrada de outro bloco para conectar “${handleName(link.handle)}”.`:'Arraste os blocos pelo título. Clique nas saídas para conectar ou escolha a próxima etapa no painel.'}</p>
     <div className="flex-1 min-h-[230px] overflow-auto bg-[#0b1422]" aria-label="Editor visual do fluxo"><div className="relative" style={{width:Math.max(1100,...draft.flow.nodes.map(n=>n.x+260)),height:Math.max(450,...draft.flow.nodes.map(n=>n.y+180)),backgroundImage:'radial-gradient(#25354d 1px, transparent 1px)',backgroundSize:'20px 20px'}}>
      <svg className="absolute inset-0 pointer-events-none" width="100%" height="100%">{draft.flow.edges.map(e=>{const a=draft.flow.nodes.find(n=>n.id===e.from),b=draft.flow.nodes.find(n=>n.id===e.to);if(!a||!b)return null;const y=a.y+100+(e.handle==='no'||e.handle==='timeout'?28:0);return <path key={e.id} d={`M ${a.x+220} ${y} C ${a.x+265} ${y},${b.x-45} ${b.y+60},${b.x} ${b.y+60}`} fill="none" stroke={e.handle==='no'?'#a78bfa':'#34d399'} strokeWidth="2"/>;})}</svg>
      {draft.flow.nodes.map(n=>{const def=DEFS[n.type],Icon=def.icon;return <div key={n.id} className={`absolute w-[220px] rounded-xl border bg-[#121f33] shadow-lg ${selected===n.id?'border-emerald-400 ring-2 ring-emerald-500/10':'border-white/15'}`} style={{left:n.x,top:n.y}}>
       <div className="flex items-center gap-2 p-3 cursor-grab touch-none border-b border-white/10" onPointerDown={e=>{setSelected(n.id);drag.current={id:n.id,pointer:e.pointerId,x:e.clientX,y:e.clientY,nx:n.x,ny:n.y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d||d.pointer!==e.pointerId)return;setDraft(r=>r?{...r,flow:{...r.flow,nodes:r.flow.nodes.map(v=>v.id===d.id?{...v,x:Math.max(10,Math.min(10000,d.nx+e.clientX-d.x)),y:Math.max(10,Math.min(6000,d.ny+e.clientY-d.y))}:v)}}:r);}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><Icon size={17} style={{color:def.color}}/><button onClick={()=>setSelected(n.id)} className="flex-1 text-left text-xs font-semibold" aria-label={`Configurar ${def.name}`}>{def.name}</button><GripHorizontal size={14} className="text-slate-500"/></div>
       <button onClick={()=>setSelected(n.id)} className="w-full px-3 py-2 text-left text-[11px] text-slate-400 h-12 overflow-hidden">{n.type==='text'?n.data.text||'Escreva sua mensagem':n.type==='audio'?n.data.url?'Áudio pronto':'Grave ou adicione um áudio':n.type==='delay'?`${n.data.minutes} minuto(s)`:n.type==='reply'?`Esperar resposta · ${n.data.minutes} min`:n.type==='condition'?n.data.keywords||'Defina a condição':n.type==='start'?draft.trigger_type==='scheduled'?'Data e hora':'Mensagem recebida':'Fluxo concluído'}</button>
       {n.type!=='start'&&<button aria-label={`Conectar entrada de ${def.name}`} onClick={()=>link?connect(link.from,link.handle,n.id):setSelected(n.id)} className={`absolute -left-2 top-12 h-4 w-4 rounded-full border-2 border-[#0b1422] ${link?'bg-amber-400':'bg-slate-400'}`}/>}
       <div className="flex flex-col gap-1 px-3 pb-2">{handles(n).map(h=><button key={h} onClick={()=>setLink({from:n.id,handle:h})} className={`flex items-center justify-between text-[11px] ${link?.from===n.id&&link.handle===h?'text-amber-300':'text-emerald-300'}`} aria-label={`Conectar ${handleName(h)} de ${def.name}`}>{handleName(h)}<ArrowDown size={13} className="-rotate-90"/></button>)}</div>
      </div>;})}
     </div></div>
    </section>
    <aside className="shrink-0 md:w-80 lg:w-96 border-t md:border-t-0 md:border-l border-white/10 p-4 space-y-4 md:overflow-y-auto bg-[#0e192a]">
     {current&&<>
      <h3 className="font-semibold text-sm">{DEFS[current.type].name}</h3>
      {current.type==='start'&&<>
       <label className="block text-xs space-y-1">Número do WhatsApp<select aria-label="Número da automação" value={draft.number_id} onChange={e=>patch({number_id:e.target.value,target_conversation_id:null})} className={inputClass}><option value="">Selecione</option>{numbers.map(n=><option key={n.id} value={n.id}>{n.label} · {n.status==='connected'?'conectado':'desconectado'}</option>)}</select></label>
       <label className="block text-xs space-y-1">Quando executar<select aria-label="Gatilho do fluxo" value={draft.trigger_type} onChange={e=>patch({trigger_type:e.target.value as Rule['trigger_type'],pause_on_human:e.target.value==='incoming'})} className={inputClass}><option value="incoming">Ao receber mensagem</option><option value="scheduled">Em uma data e hora</option></select></label>
       {draft.trigger_type==='incoming'?<>
        <label className="block text-xs space-y-1">Mensagem recebida<select aria-label="Correspondência do gatilho" value={draft.match_mode} onChange={e=>patch({match_mode:e.target.value as Rule['match_mode']})} className={inputClass}><option value="any">Qualquer mensagem</option><option value="contains">Contém uma palavra/frase</option><option value="exact">É igual à palavra/frase</option></select></label>
        {draft.match_mode!=='any'&&<textarea aria-label="Palavras do gatilho" value={draft.keywords} maxLength={1000} onChange={e=>patch({keywords:e.target.value})} placeholder="Uma palavra ou frase por linha" className={inputClass}/>}
        <label className="block text-xs space-y-1">Intervalo entre acionamentos para o mesmo contato (minutos)<input aria-label="Intervalo de acionamento" type="number" min={1} max={43200} value={draft.cooldown_minutes} onChange={e=>patch({cooldown_minutes:Number(e.target.value)})} className={inputClass}/></label>
       </>:<>
        <label className="block text-xs space-y-1">Contato<select aria-label="Contato do agendamento" value={draft.target_conversation_id||''} onChange={e=>patch({target_conversation_id:e.target.value||null})} className={inputClass}><option value="">Escolha uma conversa ativa</option>{conversations.filter(c=>c.numberId===draft.number_id).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>
        <label className="block text-xs space-y-1">Data e hora (horário do seu dispositivo)<input aria-label="Data e hora do agendamento" type="datetime-local" value={localDate(draft.scheduled_at)} onChange={e=>patch({scheduled_at:e.target.value?new Date(e.target.value).toISOString():null})} className={inputClass}/></label>
        <p className="text-[11px] text-slate-400">Executa uma vez. Para outro contato, abra ou reabra uma conversa em Mensagens. Para repetir, altere a data e salve novamente.</p>
       </>}
       <label className="block text-xs space-y-1">Prioridade (menor primeiro)<input aria-label="Prioridade do fluxo" type="number" min={1} max={1000} value={draft.priority} onChange={e=>patch({priority:Number(e.target.value)})} className={inputClass}/></label>
       <label className="flex items-start gap-2 text-xs"><input type="checkbox" checked={draft.pause_on_human} onChange={e=>patch({pause_on_human:e.target.checked})}/>Parar quando uma pessoa assumir ou pausar o bot</label><p className="text-[11px] text-slate-400">Os fluxos param quando o atendimento é encerrado.</p>
      </>}
      {current.type==='text'&&<><textarea aria-label="Texto da mensagem automática" value={current.data.text||''} maxLength={4000} onChange={e=>patchNode(current.id,{text:e.target.value})} rows={6} className={inputClass}/><p className="text-[11px] text-slate-400">Use {'{{nome}}'} para incluir o nome do contato.</p></>}
      {current.type==='audio'&&profile.company_id&&<AutomationAudio key={current.id} companyId={profile.company_id} url={current.data.url} onBusyChange={setAudioBusy} onChange={audio=>patchNode(current.id,audio)}/>}
      {current.type==='delay'&&<label className="block text-xs space-y-1">Aguardar antes da próxima etapa (minutos)<input aria-label="Minutos de espera" type="number" min={1} max={10080} value={current.data.minutes||1} onChange={e=>patchNode(current.id,{minutes:Number(e.target.value)})} className={inputClass}/><span className="block text-slate-400">A espera continua mesmo com o navegador fechado.</span></label>}
      {current.type==='reply'&&<label className="block text-xs space-y-1">Tempo máximo para o cliente responder (minutos)<input aria-label="Prazo para resposta" type="number" min={1} max={10080} value={current.data.minutes||1440} onChange={e=>patchNode(current.id,{minutes:Number(e.target.value)})} className={inputClass}/><span className="block text-slate-400">Respondeu: segue com a nova mensagem. Sem resposta: segue após o prazo.</span></label>}
      {current.type==='condition'&&<><select aria-label="Tipo de condição" value={current.data.mode||'contains'} onChange={e=>patchNode(current.id,{mode:e.target.value as 'contains'|'exact'})} className={inputClass}><option value="contains">Mensagem contém</option><option value="exact">Mensagem é igual a</option></select><textarea aria-label="Palavras da condição" placeholder="Uma palavra/frase por linha" value={current.data.keywords||''} maxLength={1000} onChange={e=>patchNode(current.id,{keywords:e.target.value})} className={inputClass}/><p className="text-[11px] text-slate-400">Compara a última mensagem do cliente (incluindo a resposta aguardada). Sem diferença de acentos ou maiúsculas.</p></>}
      {handles(current).map(h=><label key={h} className="block text-xs space-y-1">{handleName(h)}<select aria-label={`Destino ${handleName(h)}`} value={nextNode(draft.flow,current.id,h)||''} onChange={e=>e.target.value&&connect(current.id,h,e.target.value)} className={inputClass}><option value="">Escolha uma etapa</option>{draft.flow.nodes.filter(n=>n.id!==current.id&&n.type!=='start').map((n,i)=><option key={n.id} value={n.id}>{DEFS[n.type].name} · {n.data.text?.slice(0,24)||i+1}</option>)}</select></label>)}
      {current.type!=='start'&&<button onClick={()=>removeNode(current.id)} className="flex items-center gap-2 text-xs text-red-300"><Trash2 size={14}/>Remover bloco</button>}
     </>}
     <div className="border-t border-white/10 pt-4 space-y-2"><h4 className="text-xs font-semibold">Testar o caminho do fluxo</h4><input aria-label="Mensagem para simulação" value={example} onChange={e=>setExample(e.target.value)} className={inputClass}/><button onClick={simulate} className="w-full rounded-lg bg-white/10 p-2.5 text-xs">Simular fluxo</button><p className="text-[11px] text-slate-400">A simulação não envia mensagens.</p>{simulation.length>0&&<ol className="list-decimal ml-4 text-xs text-slate-300 space-y-2">{simulation.map((s,i)=><li key={i}>{s}</li>)}</ol>}</div>
    </aside>
   </div>
  </>}
 </div>;
}
