import test from 'node:test';
import assert from 'node:assert/strict';
import { matches, validateFlow, nextNode } from '../src/automation-flow.js';
import { createAutomationWorker } from '../src/automation-worker.js';
const flow={nodes:[{id:'s',type:'start',data:{}},{id:'t',type:'text',data:{text:'Olá {{nome}}'}},{id:'w',type:'delay',data:{minutes:2}},{id:'e',type:'end',data:{}}],edges:[{from:'s',to:'t',handle:'out'},{from:'t',to:'w',handle:'out'},{from:'w',to:'e',handle:'out'}]};
const makeRule=()=>({id:'rule',enabled:true,flow,trigger_type:'incoming',pause_on_human:true,match_mode:'contains',keywords:'preço'});
const makeRun=()=>({id:'run',automation_id:'rule',company_id:'company',number_id:'number',conversation_id:'conversation',flow,node_id:'t',status:'running',lease_token:'lease',steps_done:1,received_text:'PREÇO',contact_name:'Ana'});
function mock({rule=makeRule(),conversation={id:'conversation',company_id:'company',number_id:'number',status:'espera',assignee_id:null},sendError,connected=true,resume=null}={}) {
 const patches=[],sends=[],reserves=[];
 const db={from(table){let patch;const q={select(){return q},eq(){return q},order(){return q},update(v){patch=v;return q},maybeSingle(){return Promise.resolve({data:table==='message_automations'?rule:conversation})},then(resolve,reject){if(patch){patches.push({table,...patch});return Promise.resolve({error:null}).then(resolve,reject)}return Promise.resolve({data:table==='message_automations'?[rule]:[],error:null}).then(resolve,reject)}};return q},async rpc(name,args){reserves.push({name,args});return {data:name==='resume_message_automation'?resume:'run',error:null}}};
 const worker=createAutomationWorker({db,storageOrigin:'https://storage.test',connected:()=>connected,send:async payload=>{sends.push(payload);if(sendError)throw Error(sendError)},now:()=>100000,logger:{error(){}}});
 return {worker,patches,sends,reserves,db};
}
test('keyword conditions ignore accents/case but exact does not match a substring',()=>{assert(matches('contains','preço\norçamento','QUERO O PRECO'));assert(matches('exact','olá','OLA'));assert(!matches('exact','ola','ola tudo bem'));assert(!matches('contains','','oi'));});
test('flow validation rejects cycles, dangling branches, wrong storage and foreign-company recordings',()=>{assert.equal(validateFlow(flow),null);const cycle=structuredClone(flow);cycle.edges[2].to='t';assert.match(validateFlow(cycle),/anterior/);const branch=structuredClone(flow);branch.nodes[1]={id:'t',type:'condition',data:{mode:'contains',keywords:'oi'}};assert.match(validateFlow(branch),/saídas/);const audio=structuredClone(flow);audio.nodes[1]={id:'t',type:'audio',data:{url:'https://evil.test/storage/v1/object/public/wa-media/automations/company/a.webm'}};assert.match(validateFlow(audio,'https://storage.test','company'),/Workspace/);audio.nodes[1].data.url='https://storage.test/storage/v1/object/public/wa-media/automations/other/a.webm';assert.match(validateFlow(audio,'https://storage.test','company'),/Workspace/);});
test('text sends with contact name, then persists the next stage for a worker restart',async()=>{const {worker,patches,sends}=mock();await worker.process(makeRun());assert.equal(sends[0].text,'Olá Ana');assert.equal(patches[0].node_id,'w');assert.equal(patches[0].status,'queued');const restarted=mock();await restarted.worker.process({...makeRun(),node_id:'w',steps_done:2});assert.equal(restarted.sends.length,0);assert.equal(restarted.patches[0].node_id,'e');assert.equal(restarted.patches[0].due_at,new Date(220000).toISOString());await restarted.worker.process({...makeRun(),node_id:'e',steps_done:3});assert.equal(restarted.patches[1].status,'completed');assert.equal(restarted.sends.length,0);});
test('human takeover cancels without sending; disconnected number waits without advancing',async()=>{const human=mock({conversation:{company_id:'company',number_id:'number',status:'atendendo',assignee_id:'person'}});await human.worker.process(makeRun());assert.equal(human.sends.length,0);assert.equal(human.patches[0].status,'canceled');const offline=mock({connected:false});await offline.worker.process(makeRun());assert.equal(offline.sends.length,0);assert.equal(offline.patches[0].status,'queued');assert.equal(offline.patches[0].node_id,undefined);});
test('send failure is visible and is never scheduled for an automatic retry',async()=>{const {worker,patches}=mock({sendError:'WhatsApp failed'});await worker.process(makeRun());assert.equal(patches[0].status,'failed');assert.equal(patches[0].error,'WhatsApp failed');});
test('incoming match reserves one flow and overrides AI; human-owned conversations do not trigger',async()=>{const m=mock();assert(await m.worker.incoming({numberId:'number',companyId:'company',conversation:{id:'conversation'},messageKey:'wa-1',text:'qual o preço?',name:'Ana'}));assert.equal(m.reserves.filter(r=>r.name==='reserve_message_automation').length,1);assert(!await m.worker.incoming({numberId:'number',companyId:'company',conversation:{id:'conversation',assignee_id:'person'},messageKey:'wa-2',text:'preço',name:'Ana'}));assert.equal(m.reserves.filter(r=>r.name==='reserve_message_automation').length,1);});
test('branch follows the original incoming text; audio retains native audio payload',async()=>{const f=structuredClone(flow);f.nodes.push({id:'c',type:'condition',data:{mode:'contains',keywords:'preço'}});f.edges[0].to='c';f.edges.push({from:'c',to:'t',handle:'yes'},{from:'c',to:'e',handle:'no'});const m=mock();await m.worker.process({...makeRun(),flow:f,node_id:'c'});assert.equal(m.patches[0].node_id,'t');const a=structuredClone(flow);a.nodes[1]={id:'t',type:'audio',data:{url:'https://storage.test/storage/v1/object/public/wa-media/automations/company/a.webm',mime:'audio/webm'}};const audio=mock();await audio.worker.process({...makeRun(),flow:a});assert.equal(audio.sends[0].media.type,'audio');assert.equal(audio.sends[0].media.mime,'audio/webm');assert.equal(audio.patches[0].status,'queued');assert.equal(nextNode(flow,'s'),'t');});

test('wait-reply persists its deadline; next incoming resumes instead of starting a second workflow',async()=>{const f=structuredClone(flow);f.nodes[2].type='reply';f.edges[2].handle='reply';f.edges.push({from:'w',to:'e',handle:'timeout'});const m=mock();await m.worker.process({...makeRun(),node_id:'w',flow:f});assert.equal(m.sends.length,0);assert.equal(m.patches[0].status,'waiting_reply');assert.equal(m.patches[0].node_id,'w');assert.equal(m.patches[0].due_at,new Date(220000).toISOString());const reply=mock({resume:'existing-run'});assert(await reply.worker.incoming({numberId:'number',companyId:'company',conversation:{id:'conversation'},messageKey:'reply-1',text:'financeiro',name:'Ana'}));assert.equal(reply.reserves.length,1);assert.equal(reply.reserves[0].name,'resume_message_automation');});
